#!/usr/bin/env bash

export PATH=$(dirname dot-merlin-reader):$PATH

# If no dune-project of .merlin file are present in the test we write a default
# `.merlin` file to force the use of dot-merlin-reader
if [ ! -f dune-project ]; then
  touch .merlin
fi

if [ -z "$MERLIN_TEST_OCAMLLIB_PATH" ]; then
  echo >&2 "You must set the MERLIN_TEST_OCAMLLIB_PATH environment variable in your shell to run merlin tests."
  echo >&2 "It should be set to the lib/ocaml subdirectory of the directory where your flambda-backend build artifacts are installed to."
  exit 1
fi

ocamlmerlin "$@" -ocamllib-path "$MERLIN_TEST_OCAMLLIB_PATH" \
    | jq 'del(.timing)' \
    | sed -e 's:"[^"]*lib/ocaml:"lib/ocaml:g' \
    | sed -e 's:\\n:\
:g'
