#!/bin/bash

if [ -z "$MERLIN_TEST_OCAMLC_PATH" ]; then
  echo >&2 "You must set the MERLIN_TEST_OCAMLC_PATH environment variable in your shell to run merlin tests."
  echo >&2 "It should be set to the ocamlc produced from the appropriate flambda-backend build."
  exit 1
fi

"$MERLIN_TEST_OCAMLC_PATH" "$@"
