#!/bin/bash

if [ -z "$MERLIN_TEST_OCAML_PATH" ]; then
  echo >&2 "You must set the MERLIN_TEST_OCAML_PATH environment variable in your shell to run merlin tests."
  echo >&2 "It should be set to the directory where your flambda-backend build artifacts are installed."
  exit 1
fi

MERLIN_TEST_OCAMLOBJINFO_PATH="$MERLIN_TEST_OCAML_PATH/bin/ocamlobjinfo"

if [ ! -f "$MERLIN_TEST_OCAMLOBJINFO_PATH" ]; then
    echo >&2 "Error: $MERLIN_TEST_OCAMLOBJINFO_PATH does not exist."
    echo >&2 "Check that you've set MERLIN_TEST_OCAML_PATH correctly."
    exit 1
fi

"$MERLIN_TEST_OCAMLOBJINFO_PATH" "$@"
